import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'fa';

interface SettingsContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'hero.badge': 'The Future of Digital Art',
    'hero.title.prefix': 'PIMX',
    'hero.title.suffix': 'MOJI',
    'hero.description': 'Transform ordinary pixels into extraordinary ASCII, Mosaic, and Emoji masterpieces.',
    'hero.cta.start': 'START CREATING',
    'hero.cta.telegram': 'JOIN TELEGRAM',
    'stats.res': 'Res Columns',
    'stats.latency': 'Latency',
    'stats.private': 'Private',
    'stats.possibilities': 'Possibilities',
    'feature.mosaic.title': 'MOSAIC ENGINE',
    'feature.mosaic.desc': 'Experience the power of semantic art. Our proprietary mosaic algorithm deconstructs your image and rebuilds it using custom words as living pixels. It\'s not just a filter; it\'s a textual rebirth of your visual story.',
    'feature.ascii.title': 'ASCII MAPPING',
    'feature.ascii.desc': 'Where classic computer heritage meets modern precision. We utilize a sophisticated 256-level luminance mapping system to translate every photon into the perfect character, ensuring museum-grade contrast and clarity.',
    'feature.emoji.title': 'EMOJI SYNTH',
    'feature.emoji.desc': 'The ultimate pop-art revolution. Our emoji synthesizer replaces raw data with vibrant, multi-layered icons, creating a surreal visual depth that shifts and evolves depending on your perspective.',
    'ecosystem.badge': 'THE NETWORK',
    'ecosystem.title': 'THE PIMX ECOSYSTEM',
    'ecosystem.desc': "PIMXMOJI is part of a larger mission. We provide the tools you need to stay connected and creative, even in the most challenging network conditions.",
    'ecosystem.detailed_desc': 'PIMX is more than just a network; it\'s a digital fortress designed for creators, developers, and freedom seekers. In an era where digital boundaries are constantly shifting, we provide a suite of intelligent tools that ensure your voice is never silenced and your creativity knows no bounds. From ultra-secure connectivity to seamless media access, every part of our ecosystem is engineered for maximum performance and absolute privacy.',
    'ecosystem.stats.styles.label': 'Unique Styles',
    'ecosystem.stats.styles.desc': 'From classic ASCII to modern Emoji mosaics, the possibilities are infinite.',
    'ecosystem.stats.private.label': 'Private',
    'ecosystem.stats.private.desc': 'All processing happens locally in your browser. Your images never leave your device.',
    'ecosystem.stats.freedom.label': 'Freedom',
    'ecosystem.stats.freedom.desc': 'Bypass digital barriers and share your vision without limitations.',
    'ecosystem.stats.support.label': 'Support',
    'ecosystem.stats.support.desc': 'Join our community of thousands of creators on Telegram and X.',
    'howitworks.badge': 'CORE TECHNOLOGY',
    'howitworks.title': 'HOW IT WORKS',
    'howitworks.mosaic.title': 'MOSAIC ENGINE',
    'howitworks.mosaic.desc': 'Our proprietary engine breaks down your image into a grid of high-density characters, preserving detail while creating a unique aesthetic.',
    'howitworks.ascii.title': 'ASCII SYNTHESIS',
    'howitworks.ascii.desc': 'Advanced brightness mapping converts pixel data into a symphony of symbols, creating a bridge between raw data and digital art.',
    'howitworks.emoji.title': 'EMOJI MAPPING',
    'howitworks.emoji.desc': 'Transform your photos into vibrant emoji compositions. Our algorithm selects the perfect icons to represent every shade and texture.',
    'bot.pass.title': 'PIMX PASS BOT',
    'bot.pass.badge': 'ULTIMATE CONNECTIVITY',
    'bot.pass.desc': 'Your all-in-one connectivity hub. Access a massive variety of high-speed servers and tunnels including V2Ray, OpenVPN, HA Tunnel Plus, NPV Tunnel, HTTP Custom, and HTTP Injector. Simple, complete, and always updated.',
    'bot.pass.features': 'V2Ray & VPN, 256-bit Encryption, Global Servers, Smart Routing',
    'bot.play.title': 'PIMX PLAY',
    'bot.play.badge': 'ANDROID APP HUNTER',
    'bot.play.desc': 'Direct Android app downloads inside Telegram. Skip the slow app stores and external links. Just search for an app or send a Google Play link to get the APK file instantly and securely.',
    'bot.play.features': 'Direct APK Downloads, Google Play Support, Verified Files, High Speed',
    'bot.sonic.title': 'PIMX SONIC',
    'bot.sonic.badge': 'OFFLINE MUSIC PLAYER',
    'bot.sonic.desc': 'The ultimate music companion for restricted networks. Stream and download your favorite tracks directly within Telegram without worrying about external site blocks or slow loading times.',
    'bot.sonic.features': 'Direct Streaming, High Quality Audio, Telegram Integration, No Restrictions',
    'bot.pass.cta': 'START CONNECTING',
    'bot.play.cta': 'START DOWNLOADING',
    'bot.sonic.cta': 'START STREAMING',
    'bot.channel': 'CHANNEL',
    'footer.rights': '© 2026 PIMXMOJI. ALL RIGHTS RESERVED. POWERED BY PIMX_PASS.',
    'nav.home': 'Home',
    'nav.setup': 'Setup',
    'nav.result': 'Result',
    'setup.title': 'SETUP',
    'setup.back': 'BACK',
    'setup.generate': 'GENERATE',
    'setup.generating': 'GENERATING...',
    'setup.step1.title': '1. SOURCE IMAGE',
    'setup.step1.desc': 'Upload the image you want to transform.',
    'setup.upload.click': 'Click to browse files',
    'setup.upload.drag': 'JPG, PNG or WEBP up to 10MB',
    'setup.upload.change': 'Change Image',
    'setup.step2.title': '2. CONFIGURATION',
    'setup.step2.desc': 'Customize your art generation settings.',
    'preset.matrix': 'Matrix Rain',
    'preset.cyberpunk': 'Cyberpunk',
    'preset.blueprint': 'Blueprint',
    'preset.newspaper': 'Newspaper',
    'preset.retro': 'Retro Game',
    'preset.braille': 'Braille Art',
    'preset.binary': 'Binary',
    'preset.hearts': 'Emoji Hearts',
    'preset.terminal': 'Terminal',
    'preset.gold': 'Gold Luxury',
    'preset.vaporwave': 'Vaporwave',
    'preset.sketch': 'Sketch',
    'preset.neon': 'Neon Lights',
    'preset.fire': 'Fire',
    'preset.water': 'Water Waves',
    'preset.stars': 'Starry Night',
    'preset.glitch': 'Glitch Art',
    'preset.typewriter': 'Typewriter',
    'preset.blocks': 'Blocky',
    'preset.dots': 'Halftone Dots',
    'preset.nature': 'Nature',
    'preset.moon': 'Moon Phases',
    'preset.blood': 'Blood Red',
    'preset.ice': 'Ice Cold',
    'preset.money': 'Money',
    'preset.space': 'Deep Space',
    'preset.hacker': 'Hacker',
    'preset.vintage': 'Vintage Photo',
    'preset.popart': 'Pop Art',
    'preset.gothic': 'Gothic',
    'preset.candy': 'Candy',
    'preset.ocean': 'Ocean',
    'preset.sunset': 'Sunset',
    'preset.forest': 'Forest',
    'preset.desert': 'Desert',
    'preset.city': 'City Lights',
    'preset.abstract': 'Abstract',
    'preset.pixel': 'Pixel Art',
    'preset.lines': 'Line Art',
    'preset.circles': 'Circles',
    'preset.triangles': 'Triangles',
    'preset.crosses': 'Crosses',
    'preset.stars2': 'Stars 2',
    'preset.music': 'Music',
    'preset.coffee': 'Coffee',
    'preset.ocean2': 'Deep Sea',
    'preset.lava': 'Lava',
    'preset.jungle': 'Jungle',
    'preset.diamond': 'Diamond',
    'preset.toxic': 'Toxic',
    'preset.royal': 'Royal',
    'preset.ghost': 'Ghostly',
    'preset.circuit': 'Circuit',
    'preset.geometric': 'Geometric',
    'preset.alphabetic': 'Alphabetic',
    'preset.arrows': 'Arrows',
    'preset.classic_pc': 'Classic PC',
    'preset.math_art': 'Math Art',
    'preset.blocks_ext': 'Extended Blocks',
    'preset.glitch_pro': 'Glitch Pro',
    'preset.blueprint_tech': 'Tech Blueprint',
    'preset.cyber_neon': 'Cyber Neon',
    'preset.math_matrix': 'Math Matrix',
    'preset.shapes_art': 'Shapes Art',
    'mode.word': 'Word',
    'mode.ascii': 'ASCII',
    'mode.emoji': 'Emoji',
    'label.word': 'Word to repeat',
    'label.chars': 'Characters (Dark to Light)',
    'label.resolution': 'Resolution (Columns)',
    'label.spacing': 'Char Spacing',
    'label.brightness': 'Brightness',
    'label.contrast': 'Contrast',
    'label.saturation': 'Saturation',
    'label.fontFamily': 'Font Family',
    'label.fontWeight': 'Font Weight',
    'label.fontSize': 'Font Size',
    'label.colorize': 'Colorize Text',
    'label.textColor': 'Text',
    'label.bgColor': 'BG',
    'examples.title': 'ART MODES IN ACTION',
    'examples.desc': 'See how different algorithms interpret your vision.',
    'examples.mosaic.label': 'Mosaic Mode',
    'examples.ascii.label': 'ASCII Mode',
    'examples.emoji.label': 'Emoji Mode',
    'examples.matrix.label': 'Matrix Mode',
    'result.back': 'BACK TO SETUP',
    'result.title': 'RESULT',
    'result.generating.title': 'Generating Masterpiece',
    'result.generating.desc': 'Our engine is mapping pixels to characters in real-time...',
    'result.failed.title': 'Generation Failed',
    'result.failed.back': 'BACK TO SETTINGS',
    'action.download': 'DOWNLOAD IMAGE',
    'action.save': 'SAVE .TXT',
    'action.copy': 'COPY TEXT',
    'alert.upload': 'Please upload an image first!',
    'alert.copy': 'Text art copied to clipboard!',
    'alert.fail.text': 'Failed to generate text. Please try again.',
    'alert.fail.copy': 'Failed to copy text. Please try again.',
    'section.presets': 'Quick Presets',
    'section.mode': 'Art Mode & Characters',
    'section.res': 'Resolution & Spacing',
    'section.adjust': 'Image Adjustments',
    'section.typo': 'Typography & Colors',
    'history.title': 'History',
    'history.desc': 'Your recently created artworks',
    'history.empty.title': 'No history yet',
    'history.empty.desc': 'Your created masterpieces will appear here once you start generating.',
    'history.security': 'Your data is stored locally in your browser. For maximum security, nothing is uploaded to our servers.',
    'history.action.use': 'Use Style',
    'history.action.download': 'Download',
    'history.action.delete': 'Delete',
  },
  fa: {
    'hero.badge': 'آینده هنر دیجیتال',
    'hero.title.prefix': 'PIMX',
    'hero.title.suffix': 'MOJI',
    'hero.description': 'پیکسل‌های معمولی را به شاهکارهای ASCII، Mosaic و Emoji تبدیل کنید.',
    'hero.cta.start': 'شروع ساخت',
    'hero.cta.telegram': 'عضویت در تلگرام',
    'stats.res': 'ستون رزولوشن',
    'stats.latency': 'تأخیر',
    'stats.private': 'خصوصی',
    'stats.possibilities': 'احتمالات',
    'feature.mosaic.title': 'MOSAIC ENGINE',
    'feature.mosaic.desc': 'قدرت هنر معنایی را تجربه کنید. الگوریتم اختصاصی ما تصویر شما را واسازی کرده و با استفاده از کلمات دلخواه به عنوان پیکسل‌های زنده، آن را دوباره می‌سازد. این فقط یک فیلتر نیست؛ تولد دوباره متنی داستان بصری شماست.',
    'feature.ascii.title': 'ASCII MAPPING',
    'feature.ascii.desc': 'جایی که میراث کلاسیک کامپیوتر با دقت مدرن ملاقات می‌کند. ما از یک سیستم پیشرفته نگاشت درخشندگی ۲۵۶ سطحی استفاده می‌کنیم تا هر فوتون را به کاراکتر ایده‌آل ترجمه کنیم و کنتراست و وضوحی در سطح موزه‌ها را تضمین کنیم.',
    'feature.emoji.title': 'EMOJI SYNTH',
    'feature.emoji.desc': 'انقلاب نهایی پاپ آرت. سینت سایزر ایموجی ما داده‌های خام را با آیکون‌های پر جنب و جوش و چند لایه جایگزین می‌کند و عمق بصوی سورئالی ایجاد می‌کند که بسته به زاویه دید شما تغییر کرده و تکامل می‌یابد.',
    'ecosystem.badge': 'شبکه',
    'ecosystem.title': 'اکوسیستم PIMX',
    'ecosystem.desc': "PIMXMOJI بخشی از یک ماموریت بزرگتر است. ما ابزارهایی را در اختیار شما قرار می‌دهیم تا حتی در سخت‌ترین شرایط شبکه، متصل و خلاق بمانید.",
    'ecosystem.detailed_desc': 'PIMX فراتر از یک شبکه است؛ این یک دژ دیجیتال است که برای خالقان، توسعه‌دهندگان و جویندگان آزادی طراحی شده است. در عصری که مرزهای دیجیتال مدام در حال تغییر هستند، ما مجموعه‌ای از ابزارهای هوشمند را ارائه می‌دهیم که تضمین می‌کنند صدای شما هرگز خاموش نمی‌شود و خلاقیت شما هیچ مرزی نمی‌شناسد. از اتصال فوق امن گرفته تا دسترسی یکپارچه به رسانه‌ها، هر بخش از اکوسیستم ما برای حداکثر کارایی و حریم خصوصی مطلق مهندسی شده است.',
    'ecosystem.stats.styles.label': 'سبک‌های منحصر به فرد',
    'ecosystem.stats.styles.desc': 'از ASCII کلاسیک تا موزاییک‌های ایموجی مدرن، احتمالات بی‌پایان هستند.',
    'ecosystem.stats.private.label': 'خصوصی',
    'ecosystem.stats.private.desc': 'تمام پردازش‌ها به صورت محلی در مرورگر شما انجام می‌شود. تصاویر شما هرگز دستگاه شما را ترک نمی‌کنند.',
    'ecosystem.stats.freedom.label': 'آزادی',
    'ecosystem.stats.freedom.desc': 'موانع دیجیتال را دور بزنید و دیدگاه خود را بدون محدودیت به اشتراک بگذارید.',
    'ecosystem.stats.support.label': 'پشتیبانی',
    'ecosystem.stats.support.desc': 'به جامعه هزاران نفری ما در تلگرام و X بپیوندید.',
    'howitworks.badge': 'تکنولوژی هسته',
    'howitworks.title': 'چگونه کار می‌کند',
    'howitworks.mosaic.title': 'موتور موزاییک',
    'howitworks.mosaic.desc': 'موتور اختصاصی ما تصویر شما را به شبکه‌ای از کاراکترهای با تراکم بالا تبدیل می‌کند و جزئیات را حفظ کرده و زیبایی منحصر به فردی خلق می‌کند.',
    'howitworks.ascii.title': 'سنتز ASCII',
    'howitworks.ascii.desc': 'نگاشت پیشرفته درخشندگی، داده‌های پیکسل را به سمفونی از نمادها تبدیل می‌کند و پلی بین داده‌های خام و هنر دیجیتال می‌سازد.',
    'howitworks.emoji.title': 'نگاشت ایموجی',
    'howitworks.emoji.desc': 'عکس‌های خود را به ترکیبات ایموجی پر جنب و جوش تبدیل کنید. الگوریتم ما آیکون‌های عالی را برای نمایش هر سایه و بافت انتخاب می‌کند.',
    'bot.pass.title': 'PIMX PASS BOT',
    'bot.pass.badge': 'اتصال نهایی',
    'bot.pass.desc': 'مرکز اتصال همه کاره شما. دسترسی به تنوع گسترده‌ای از سرورها و تانل‌های پرسرعت از جمله V2Ray، OpenVPN، HA Tunnel Plus، NPV Tunnel، HTTP Custom و HTTP Injector. ساده، کامل و همیشه به‌روز.',
    'bot.pass.features': 'V2Ray و VPN، رمزنگاری ۲۵۶ بیتی، سرورهای جهانی، مسیریابی هوشمند',
    'bot.play.title': 'PIMX PLAY',
    'bot.play.badge': 'شکارچی اپلیکیشن اندروید',
    'bot.play.desc': 'دانلود مستقیم اپلیکیشن‌های اندروید داخل تلگرام. از استورهای کند و لینک‌های خارجی عبور کنید. فقط نام برنامه را جستجو کنید یا لینک گوگل پلی بفرستید تا فایل APK را فوری و ایمن دریافت کنید.',
    'bot.play.features': 'دانلود مستقیم APK، پشتیبانی از گوگل پلی، فایل‌های تایید شده، سرعت بالا',
    'bot.sonic.title': 'PIMX SONIC',
    'bot.sonic.badge': 'پخش‌کننده موسیقی آفلاین',
    'bot.sonic.desc': 'همراه نهایی موسیقی برای شبکه‌های محدود شده. آهنگ‌های مورد علاقه خود را مستقیماً در تلگرام پخش و دانلود کنید بدون نگرانی از مسدود شدن سایت‌های خارجی یا سرعت پایین بارگذاری.',
    'bot.sonic.features': 'پخش مستقیم، کیفیت صدای بالا، ادغام با تلگرام، بدون محدودیت',
    'bot.pass.cta': 'شروع اتصال',
    'bot.play.cta': 'شروع دانلود',
    'bot.sonic.cta': 'شروع پخش',
    'bot.channel': 'کانال',
    'footer.rights': '© ۲۰۲۶ PIMXMOJI. تمامی حقوق محفوظ است. قدرت گرفته از PIMX_PASS.',
    'nav.home': 'خانه',
    'nav.setup': 'تنظیمات',
    'nav.result': 'نتیجه',
    'setup.title': 'تنظیمات',
    'setup.back': 'بازگشت',
    'setup.generate': 'تولید',
    'setup.generating': 'در حال تولید...',
    'setup.step1.title': '۱. تصویر منبع',
    'setup.step1.desc': 'تصویری که می‌خواهید تبدیل کنید را آپلود کنید.',
    'setup.upload.click': 'برای انتخاب فایل کلیک کنید',
    'setup.upload.drag': 'JPG، PNG یا WEBP تا ۱۰ مگابایت',
    'setup.upload.change': 'تغییر تصویر',
    'setup.step2.title': '۲. پیکربندی',
    'setup.step2.desc': 'تنظیمات تولید هنر خود را سفارشی کنید.',
    'preset.matrix': 'باران ماتریکس',
    'preset.cyberpunk': 'سایبرپانک',
    'preset.blueprint': 'نقشه فنی',
    'preset.newspaper': 'روزنامه',
    'preset.retro': 'بازی رترو',
    'preset.braille': 'هنر بریل',
    'preset.binary': 'باینری',
    'preset.hearts': 'قلب‌های ایموجی',
    'preset.terminal': 'ترمینال',
    'preset.gold': 'لوکس طلایی',
    'preset.vaporwave': 'ویپورویو',
    'preset.sketch': 'طراحی',
    'preset.neon': 'نورهای نئون',
    'preset.fire': 'آتش',
    'preset.water': 'امواج آب',
    'preset.stars': 'شب ستاره‌ای',
    'preset.glitch': 'هنر گلیچ',
    'preset.typewriter': 'ماشین تحریر',
    'preset.blocks': 'بلوکی',
    'preset.dots': 'نقاط هافتون',
    'preset.nature': 'طبیعت',
    'preset.moon': 'فازهای ماه',
    'preset.blood': 'قرمز خونی',
    'preset.ice': 'یخ زده',
    'preset.money': 'پول',
    'preset.space': 'فضای عمیق',
    'preset.hacker': 'هکر',
    'preset.vintage': 'عکس قدیمی',
    'preset.popart': 'پاپ آرت',
    'preset.gothic': 'گوتیک',
    'preset.candy': 'آبنبات',
    'preset.ocean': 'اقیانوس',
    'preset.sunset': 'غروب',
    'preset.forest': 'جنگل',
    'preset.desert': 'کویر',
    'preset.city': 'چراغ‌های شهر',
    'preset.abstract': 'انتزاعی',
    'preset.pixel': 'هنر پیکسلی',
    'preset.lines': 'هنر خطی',
    'preset.circles': 'دایره‌ها',
    'preset.triangles': 'مثلث‌ها',
    'preset.crosses': 'ضربدرها',
    'preset.stars2': 'ستاره‌ها ۲',
    'preset.music': 'موسیقی',
    'preset.coffee': 'قهوه',
    'preset.ocean2': 'دریای عمیق',
    'preset.lava': 'گدازه',
    'preset.jungle': 'جنگل',
    'preset.diamond': 'الماس',
    'preset.toxic': 'سمی',
    'preset.royal': 'سلطنتی',
    'preset.ghost': 'شبح‌وار',
    'preset.circuit': 'مدار',
    'preset.geometric': 'هندسی',
    'preset.alphabetic': 'حروف الفبا',
    'preset.arrows': 'فلش‌ها',
    'preset.classic_pc': 'کلاسیک PC',
    'preset.math_art': 'هنر ریاضی',
    'preset.blocks_ext': 'بلوک‌های پیشرفته',
    'preset.glitch_pro': 'گلیچ حرفه‌ای',
    'preset.blueprint_tech': 'نقشه فنی',
    'preset.cyber_neon': 'سایبر نئون',
    'preset.math_matrix': 'ماتریکس ریاضی',
    'preset.shapes_art': 'هنر اشکال',
    'preset.cyber_grid': 'شبکه سایبری',
    'preset.neon_tokyo': 'توکیو نئونی',
    'preset.hologram': 'هولوگرام',
    'preset.synthwave': 'سینث‌ویو',
    'preset.blood_moon': 'ماه خونین',
    'preset.alien_tech': 'فناوری بیگانه',
    'preset.matrix_red': 'ماتریکس قرمز',
    'preset.golden_ratio': 'نسبت طلایی',
    'preset.crystal': 'کریستال',
    'preset.steampunk': 'استیم‌پانک',
    'preset.gothic_rose': 'رز گوتیک',
    'preset.cyber_city': 'شهر سایبری',
    'preset.retro_wave': 'رترو ویو',
    'preset.neon_sign': 'تابلو نئونی',
    'preset.hacker_green': 'هکر سبز',
    'preset.vintage_sepia': 'سپیا وینتیج',
    'preset.pop_art_dots': 'نقاط پاپ‌آرت',
    'preset.comic_book': 'کمیک‌بوک',
    'preset.watercolor': 'آبرنگ',
    'preset.oil_painting': 'نقاشی روغنی',
    'preset.stained_glass': 'شیشه رنگی',
    'preset.ascii_classic': 'ASCII کلاسیک',
    'preset.braille_dark': 'بریل تیره',
    'preset.binary_code': 'کد باینری',
    'preset.hex_code': 'کد هگز',
    'preset.dna_strand': 'رشته DNA',
    'preset.constellation': 'صورت فلکی',
    'preset.snowfall': 'بارش برف',
    'preset.autumn': 'پاییز',
    'preset.spring': 'بهار',
    'preset.summer': 'تابستان',
    'preset.volcano': 'آتشفشان',
    'preset.thunder': 'رعد و برق',
    'preset.tornado': 'گردباد',
    'preset.earthquake': 'زلزله',
    'preset.tsunami': 'سونامی',
    'preset.meteor': 'شهاب‌سنگ',
    'preset.black_hole': 'سیاه‌چاله',
    'preset.supernova': 'ابرنواختر',
    'preset.nebula': 'سحابی',
    'preset.galaxy': 'کهکشان',
    'preset.milky_way': 'راه شیری',
    'preset.solar_system': 'منظومه شمسی',
    'preset.alien_planet': 'سیاره بیگانه',
    'preset.robot_army': 'ارتش ربات‌ها',
    'preset.cyborg': 'سایبورگ',
    'preset.ai_brain': 'مغز هوش مصنوعی',
    'preset.quantum': 'کوانتوم',
    'preset.vr_world': 'دنیای VR',
    'preset.ar_vision': 'دید AR',
    'preset.metaverse': 'متاورس',
    'preset.blockchain': 'بلاکچین',
    'preset.crypto': 'کریپتو',
    'preset.nft_art': 'هنر NFT',
    'preset.web3': 'وب ۳',
    'preset.security': 'امنیت',
    'preset.data_breach': 'نشت داده',
    'preset.firewall': 'فایروال',
    'preset.virus': 'ویروس',
    'preset.malware': 'بدافزار',
    'preset.ransomware': 'باج‌افزار',
    'preset.phishing': 'فیشینگ',
    'preset.spam': 'اسپم',
    'preset.ddos': 'حمله DDoS',
    'preset.botnet': 'بات‌نت',
    'preset.zero_day': 'زیرو‌دی',
    'preset.exploit': 'اکسپلویت',
    'preset.patch': 'پچ',
    'preset.update': 'آپدیت',
    'preset.upgrade': 'ارتقا',
    'preset.downgrade': 'تنزل نسخه',
    'preset.crash': 'کرش',
    'preset.reboot': 'راه‌اندازی مجدد',
    'preset.shutdown': 'خاموشی',
    'preset.startup': 'راه‌اندازی',
    'preset.login': 'ورود',
    'preset.logout': 'خروج',
    'preset.register': 'ثبت‌نام',
    'preset.profile': 'پروفایل',
    'preset.settings': 'تنظیمات',
    'preset.dashboard': 'داشبورد',
    'preset.analytics': 'آنالیتیکس',
    'preset.metrics': 'متریک‌ها',
    'preset.statistics': 'آمار',
    'preset.data_viz': 'تصویرسازی داده',
    'preset.infographic': 'اینفوگرافیک',
    'preset.chart': 'چارت',
    'preset.graph': 'نمودار',
    'mode.word': 'Word',
    'mode.ascii': 'ASCII',
    'mode.emoji': 'Emoji',
    'label.word': 'کلمه برای تکرار',
    'label.chars': 'کاراکترها (تیره به روشن)',
    'label.resolution': 'رزولوشن (ستون‌ها)',
    'label.spacing': 'فاصله کاراکتر',
    'label.brightness': 'روشنایی',
    'label.contrast': 'کنتراست',
    'label.saturation': 'اشباع رنگ',
    'label.fontFamily': 'خانواده فونت',
    'label.fontWeight': 'وزن فونت',
    'label.fontSize': 'اندازه قلم',
    'label.colorize': 'رنگی کردن متن',
    'label.textColor': 'متن',
    'label.bgColor': 'پس‌زمینه',
    'examples.title': 'حالت‌های هنری در عمل',
    'examples.desc': 'ببینید چگونه الگوریتم‌های مختلف دیدگاه شما را تفسیر می‌کنند.',
    'examples.mosaic.label': 'Mosaic Mode',
    'examples.ascii.label': 'ASCII Mode',
    'examples.emoji.label': 'Emoji Mode',
    'examples.matrix.label': 'Matrix Mode',
    'result.back': 'بازگشت به تنظیمات',
    'result.title': 'نتیجه',
    'result.generating.title': 'تولید شاهکار',
    'result.generating.desc': 'موتور ما در حال نگاشت پیکسل‌ها به کاراکترها به صورت بلادرنگ است...',
    'result.failed.title': 'تولید ناموفق بود',
    'result.failed.back': 'بازگشت به تنظیمات',
    'action.download': 'دانلود تصویر',
    'action.save': 'ذخیره .TXT',
    'action.copy': 'کپی متن',
    'alert.upload': 'لطفاً ابتدا یک تصویر آپلود کنید!',
    'alert.copy': 'هنر متنی در کلیپ‌بورد کپی شد!',
    'alert.fail.text': 'تولید متن ناموفق بود. لطفاً دوباره تلاش کنید.',
    'alert.fail.copy': 'کپی متن ناموفق بود. لطفاً دوباره تلاش کنید.',
    'section.presets': 'پریست‌های سریع',
    'section.mode': 'حالت هنر و کاراکترها',
    'section.res': 'رزولوشن و فاصله',
    'section.adjust': 'تنظیمات تصویر',
    'section.typo': 'تایپوگرافی و رنگ‌ها',
    'history.title': 'تاریخچه',
    'history.desc': 'تصاویر اخیراً ساخته‌شده شما در این بخش نمایش داده می‌شوند',
    'history.empty.title': 'هنوز تاریخچه‌ای وجود ندارد',
    'history.empty.desc': 'بعد از تولید تصویر، خروجی‌های شما در این بخش ظاهر می‌شوند.',
    'history.security': 'داده‌های شما فقط در مرورگر خودتان ذخیره می‌شود و چیزی به سرورهای ما ارسال نمی‌شود.',
    'history.action.use': 'استفاده از سبک',
    'history.action.download': 'دانلود',
    'history.action.delete': 'حذف',
  }
};

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('theme') as Theme;
      if (saved) return saved;
      if (window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
        return 'light';
      }
    }
    return 'dark';
  });
  
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language;
      if (saved) return saved;
    }
    return 'en';
  });

  useEffect(() => {
    // Apply theme
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark');
    root.classList.add(theme);
    localStorage.setItem('theme', theme);
  }, [theme]);

  useEffect(() => {
    // Apply language
    const root = window.document.documentElement;
    root.lang = language;
    root.dir = 'ltr'; // Always keep ltr on html to keep scrollbar on right
    localStorage.setItem('language', language);
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fa' : 'en');
  };

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <SettingsContext.Provider value={{ theme, language, toggleTheme, toggleLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
}
