import { ArtOptions } from '../utils/imageProcessing';

export interface Preset {
  id: string;
  name: string;
  color: string;
  options: Partial<ArtOptions>;
  previewImg: string; // URL to a preview image
}

export const PRESETS: Preset[] = [
  {
    id: 'matrix',
    name: 'Matrix Rain',
    color: 'text-green-500 dark:text-green-400',
    options: { mode: 'ascii', chars: '      .:-+=;ﾘｹﾒｶﾀｼﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ', textColor: '#00ff41', bgColor: '#000000', brightness: 110, contrast: 220, shadowBlur: 0, shadowColor: '#00ff41', threshold: 40, spacing: 1.2 },
    previewImg: 'https://picsum.photos/seed/matrix/400/400'
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    color: 'text-pink-500 dark:text-pink-400',
    options: { mode: 'ascii', chars: '░▒▓█', colorize: true, bgColor: '#05000a', contrast: 170, saturation: 180, shadowBlur: 10, shadowColor: '#ff00ff' },
    previewImg: 'https://picsum.photos/seed/cyberpunk/400/400'
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    color: 'text-blue-500 dark:text-blue-400',
    options: { mode: 'ascii', chars: ' .|+*#', textColor: '#ffffff', bgColor: '#0a3d91', invert: true, contrast: 130 },
    previewImg: 'https://picsum.photos/seed/blueprint/400/400'
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    color: 'text-zinc-600 dark:text-zinc-300',
    options: { mode: 'ascii', chars: ' .,:;irsXA253hMHGS#9B&@', textColor: '#111111', bgColor: '#f4f4f0', invert: true, fontFamily: 'serif', contrast: 140, saturation: 0 },
    previewImg: 'https://picsum.photos/seed/newspaper/400/400'
  },
  {
    id: 'retro',
    name: 'Retro Game',
    color: 'text-orange-500 dark:text-orange-400',
    options: { mode: 'mosaic', chars: '■□', colorize: true, bgColor: '#000000', resolution: 80, contrast: 160 },
    previewImg: 'https://picsum.photos/seed/retro/400/400'
  },
  {
    id: 'braille',
    name: 'Braille Art',
    color: 'text-zinc-600 dark:text-zinc-300',
    options: { mode: 'ascii', chars: ' ⠁⠃⠇⡇⣇⣧⣷⣿', colorize: true, bgColor: '#000000' },
    previewImg: 'https://picsum.photos/seed/braille/400/400'
  },
  {
    id: 'binary',
    name: 'Binary',
    color: 'text-zinc-600 dark:text-zinc-300',
    options: { mode: 'ascii', chars: '01', textColor: '#ffffff', bgColor: '#000000', contrast: 200 },
    previewImg: 'https://picsum.photos/seed/binary/400/400'
  },
  {
    id: 'hearts',
    name: 'Emoji Hearts',
    color: 'text-pink-500 dark:text-pink-400',
    options: { mode: 'emoji', chars: '🖤🤎❤️🧡💛💚💙💜🤍', bgColor: '#000000' },
    previewImg: 'https://picsum.photos/seed/hearts/400/400'
  },
  {
    id: 'terminal',
    name: 'Terminal',
    color: 'text-emerald-500 dark:text-emerald-400',
    options: { mode: 'ascii', chars: ' #_@', textColor: '#00ff00', bgColor: '#000000', fontFamily: 'monospace', contrast: 150 },
    previewImg: 'https://picsum.photos/seed/terminal/400/400'
  },
  {
    id: 'gold',
    name: 'Gold Luxury',
    color: 'text-yellow-600 dark:text-yellow-500',
    options: { mode: 'ascii', chars: ' .:+*#%@', textColor: '#ffd700', bgColor: '#1a1a1a', shadowBlur: 8, shadowColor: '#ffd700', contrast: 130 },
    previewImg: 'https://picsum.photos/seed/gold/400/400'
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    color: 'text-cyan-500 dark:text-cyan-400',
    options: { mode: 'ascii', chars: '░▒▓█', colorize: true, bgColor: '#2d004d', saturation: 200, contrast: 150, shadowBlur: 15, shadowColor: '#00ffff' },
    previewImg: 'https://picsum.photos/seed/vaporwave/400/400'
  },
  {
    id: 'sketch',
    name: 'Sketch',
    color: 'text-zinc-500 dark:text-zinc-400',
    options: { mode: 'ascii', chars: ' /\\|-_', textColor: '#000000', bgColor: '#ffffff', invert: true, contrast: 180, saturation: 0 },
    previewImg: 'https://picsum.photos/seed/sketch/400/400'
  },
  { id: 'neon', name: 'Neon Lights', color: 'text-fuchsia-500', options: { mode: 'ascii', chars: ' .:-=+*#%@', colorize: true, bgColor: '#000000', shadowBlur: 10, shadowColor: '#ff00ff', contrast: 150 }, previewImg: 'https://picsum.photos/seed/neon/400/400' },
  { id: 'fire', name: 'Fire', color: 'text-orange-500', options: { mode: 'emoji', chars: '🌑🔥💥', bgColor: '#000000', contrast: 150 }, previewImg: 'https://picsum.photos/seed/fire/400/400' },
  { id: 'water', name: 'Water Waves', color: 'text-blue-400', options: { mode: 'ascii', chars: ' ░▒▓█', textColor: '#00ffff', bgColor: '#000033', contrast: 120 }, previewImg: 'https://picsum.photos/seed/water/400/400' },
  { id: 'stars', name: 'Starry Night', color: 'text-yellow-300', options: { mode: 'ascii', chars: ' .✧✦★', textColor: '#ffffff', bgColor: '#000011', contrast: 180 }, previewImg: 'https://picsum.photos/seed/stars/400/400' },
  { id: 'glitch', name: 'Glitch Art', color: 'text-red-500', options: { mode: 'ascii', chars: ' █▓▒░', colorize: true, bgColor: '#000000', contrast: 200, saturation: 150 }, previewImg: 'https://picsum.photos/seed/glitch/400/400' },
  { id: 'typewriter', name: 'Typewriter', color: 'text-zinc-700', options: { mode: 'ascii', chars: ' .,:;I!i><~+_-?][}{1)(|/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$', textColor: '#222222', bgColor: '#f0f0f0', fontFamily: 'monospace', invert: true }, previewImg: 'https://picsum.photos/seed/typewriter/400/400' },
  { id: 'blocks', name: 'Blocky', color: 'text-emerald-500', options: { mode: 'mosaic', chars: '██', colorize: true, bgColor: '#000000', resolution: 60 }, previewImg: 'https://picsum.photos/seed/blocks/400/400' },
  { id: 'dots', name: 'Halftone Dots', color: 'text-zinc-500', options: { mode: 'ascii', chars: ' ⋅∘○◍●', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/dots/400/400' },
  { id: 'nature', name: 'Nature', color: 'text-green-600', options: { mode: 'emoji', chars: '🌱🌿🌳🌲🍃', bgColor: '#000000' }, previewImg: 'https://picsum.photos/seed/nature/400/400' },
  { id: 'moon', name: 'Moon Phases', color: 'text-zinc-300', options: { mode: 'emoji', chars: '🌑🌒🌓🌔🌕', bgColor: '#000000' }, previewImg: 'https://picsum.photos/seed/moon/400/400' },
  { id: 'blood', name: 'Blood Red', color: 'text-red-600', options: { mode: 'ascii', chars: ' .:-=+*#%@', textColor: '#ff0000', bgColor: '#110000', contrast: 150 }, previewImg: 'https://picsum.photos/seed/blood/400/400' },
  { id: 'ice', name: 'Ice Cold', color: 'text-cyan-300', options: { mode: 'ascii', chars: ' ❄❅❆', textColor: '#aaffff', bgColor: '#001122', contrast: 130 }, previewImg: 'https://picsum.photos/seed/ice/400/400' },
  { id: 'money', name: 'Money', color: 'text-green-500', options: { mode: 'emoji', chars: '💵💸💰🤑', bgColor: '#000000' }, previewImg: 'https://picsum.photos/seed/money/400/400' },
  { id: 'space', name: 'Deep Space', color: 'text-purple-500', options: { mode: 'emoji', chars: '🌌🌠🪐☄️', bgColor: '#000000' }, previewImg: 'https://picsum.photos/seed/space/400/400' },
  { id: 'hacker', name: 'Hacker', color: 'text-green-400', options: { mode: 'ascii', chars: ' 01', textColor: '#00ff00', bgColor: '#000000', fontFamily: 'monospace', contrast: 180 }, previewImg: 'https://picsum.photos/seed/hacker/400/400' },
  { id: 'vintage', name: 'Vintage Photo', color: 'text-yellow-700', options: { mode: 'ascii', chars: ' ░▒▓█', textColor: '#5c4033', bgColor: '#f5deb3', invert: true, contrast: 110 }, previewImg: 'https://picsum.photos/seed/vintage/400/400' },
  { id: 'popart', name: 'Pop Art', color: 'text-pink-500', options: { mode: 'mosaic', chars: 'POP!', colorize: true, bgColor: '#ffff00', contrast: 200, saturation: 200 }, previewImg: 'https://picsum.photos/seed/popart/400/400' },
  { id: 'gothic', name: 'Gothic', color: 'text-zinc-800', options: { mode: 'ascii', chars: ' ⸸☠⛧', textColor: '#ffffff', bgColor: '#000000', contrast: 160 }, previewImg: 'https://picsum.photos/seed/gothic/400/400' },
  { id: 'candy', name: 'Candy', color: 'text-pink-400', options: { mode: 'emoji', chars: '🍬🍭🍫🍩', bgColor: '#ffb6c1' }, previewImg: 'https://picsum.photos/seed/candy/400/400' },
  { id: 'ocean', name: 'Ocean', color: 'text-blue-600', options: { mode: 'emoji', chars: '🌊🐋🐬🐟', bgColor: '#000022' }, previewImg: 'https://picsum.photos/seed/ocean/400/400' },
  { id: 'sunset', name: 'Sunset', color: 'text-orange-400', options: { mode: 'ascii', chars: ' ░▒▓█', colorize: true, bgColor: '#220000', saturation: 150 }, previewImg: 'https://picsum.photos/seed/sunset/400/400' },
  { id: 'forest', name: 'Forest', color: 'text-green-700', options: { mode: 'ascii', chars: ' ░▒▓█', colorize: true, bgColor: '#001100', saturation: 120 }, previewImg: 'https://picsum.photos/seed/forest/400/400' },
  { id: 'desert', name: 'Desert', color: 'text-yellow-600', options: { mode: 'ascii', chars: ' ░▒▓█', colorize: true, bgColor: '#331100', saturation: 130 }, previewImg: 'https://picsum.photos/seed/desert/400/400' },
  { id: 'city', name: 'City Lights', color: 'text-blue-300', options: { mode: 'ascii', chars: ' .:-=+*#%@', colorize: true, bgColor: '#000011', contrast: 140 }, previewImg: 'https://picsum.photos/seed/city/400/400' },
  { id: 'abstract', name: 'Abstract', color: 'text-purple-400', options: { mode: 'mosaic', chars: '▲▼◀▶', colorize: true, bgColor: '#000000', resolution: 50 }, previewImg: 'https://picsum.photos/seed/abstract/400/400' },
  { id: 'pixel', name: 'Pixel Art', color: 'text-zinc-400', options: { mode: 'mosaic', chars: '■', colorize: true, bgColor: '#000000', resolution: 40 }, previewImg: 'https://picsum.photos/seed/pixel/400/400' },
  { id: 'lines', name: 'Line Art', color: 'text-zinc-600', options: { mode: 'ascii', chars: ' ─│┌┐└┘├┤┬┴┼', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/lines/400/400' },
  { id: 'circles', name: 'Circles', color: 'text-zinc-500', options: { mode: 'ascii', chars: ' ◦○◎◉●', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/circles/400/400' },
  { id: 'triangles', name: 'Triangles', color: 'text-zinc-500', options: { mode: 'ascii', chars: ' △▲▽▼', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/triangles/400/400' },
  { id: 'crosses', name: 'Crosses', color: 'text-zinc-500', options: { mode: 'ascii', chars: ' ✕✖✗✘', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/crosses/400/400' },
  { id: 'stars2', name: 'Stars 2', color: 'text-yellow-400', options: { mode: 'ascii', chars: ' ☆★', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/stars2/400/400' },
  { id: 'music', name: 'Music', color: 'text-blue-500', options: { mode: 'ascii', chars: ' ♩♪♫♬', textColor: '#000000', bgColor: '#ffffff', invert: true }, previewImg: 'https://picsum.photos/seed/music/400/400' },
  { id: 'coffee', name: 'Coffee', color: 'text-amber-800', options: { mode: 'ascii', chars: ' .:-=+*#%@', textColor: '#4b3621', bgColor: '#f5f5dc', contrast: 130 }, previewImg: 'https://picsum.photos/seed/coffee/400/400' },
  { id: 'ocean2', name: 'Deep Sea', color: 'text-blue-900', options: { mode: 'ascii', chars: ' ░▒▓█', textColor: '#00ffff', bgColor: '#000033', contrast: 150 }, previewImg: 'https://picsum.photos/seed/ocean2/400/400' },
  { id: 'lava', name: 'Lava', color: 'text-red-500', options: { mode: 'ascii', chars: ' .:-=+*#%@', textColor: '#ff4500', bgColor: '#1a0000', shadowBlur: 10, shadowColor: '#ff0000' }, previewImg: 'https://picsum.photos/seed/lava/400/400' },
  { id: 'jungle', name: 'Jungle', color: 'text-green-800', options: { mode: 'emoji', chars: '🌿🍃🐒🦜🐍', bgColor: '#001a00' }, previewImg: 'https://picsum.photos/seed/jungle/400/400' },
  { id: 'diamond', name: 'Diamond', color: 'text-cyan-100', options: { mode: 'ascii', chars: ' .:+*#', textColor: '#e0ffff', bgColor: '#000000', shadowBlur: 15, shadowColor: '#00ffff' }, previewImg: 'https://picsum.photos/seed/diamond/400/400' },
  { id: 'toxic', name: 'Toxic', color: 'text-lime-400', options: { mode: 'ascii', chars: ' ☣☢☠', textColor: '#39ff14', bgColor: '#000000', contrast: 200 }, previewImg: 'https://picsum.photos/seed/toxic/400/400' },
  { id: 'royal', name: 'Royal', color: 'text-purple-600', options: { mode: 'ascii', chars: ' ⚜👑💎', textColor: '#ffd700', bgColor: '#2e0854', contrast: 140 }, previewImg: 'https://picsum.photos/seed/royal/400/400' },
  { id: 'ghost', name: 'Ghostly', color: 'text-zinc-400', options: { mode: 'ascii', chars: ' ░▒▓█', textColor: '#ffffff', bgColor: '#000000', contrast: 80, brightness: 150 }, previewImg: 'https://picsum.photos/seed/ghost/400/400' },
  { id: 'circuit', name: 'Circuit', color: 'text-emerald-400', options: { mode: 'ascii', chars: ' ┌┐└┘├┤┬┴┼', textColor: '#00ff00', bgColor: '#000000', contrast: 180 }, previewImg: 'https://picsum.photos/seed/circuit/400/400' },
  { id: 'geometric', name: 'Geometric', color: 'text-indigo-400', options: { mode: 'ascii', chars: ' ○◌◍◎●◐◑◒◓◔◕', colorize: true, bgColor: '#000000', contrast: 150 }, previewImg: 'https://picsum.photos/seed/geometric/400/400' },
  { id: 'alphabetic', name: 'Alphabetic', color: 'text-zinc-400', options: { mode: 'ascii', chars: ' ABCDEFGHIJKLMNOPQRSTUVWXYZ', textColor: '#ffffff', bgColor: '#000000', contrast: 160 }, previewImg: 'https://picsum.photos/seed/alpha/400/400' },
  { id: 'arrows', name: 'Arrows', color: 'text-orange-400', options: { mode: 'ascii', chars: ' ←↑→↓↔↕↖↗↘↙', colorize: true, bgColor: '#000000', contrast: 140 }, previewImg: 'https://picsum.photos/seed/arrows/400/400' },
  { id: 'classic_pc', name: 'Classic PC', color: 'text-zinc-300', options: { mode: 'ascii', chars: ' ☺☻♥♦♣♠•◘○◙♂♀♪♫☼', textColor: '#aaaaaa', bgColor: '#000000', fontFamily: 'monospace', contrast: 170 }, previewImg: 'https://picsum.photos/seed/pc/400/400' },
  { id: 'math_art', name: 'Math Art', color: 'text-blue-400', options: { mode: 'ascii', chars: ' ±×÷√∞∟∠∡∢∣∤∥∦', textColor: '#00aaff', bgColor: '#000000', contrast: 150 }, previewImg: 'https://picsum.photos/seed/math/400/400' },
  { id: 'blocks_ext', name: 'Extended Blocks', color: 'text-zinc-500', options: { mode: 'ascii', chars: ' ▀   ▂▃▄▅▆▇█▉▊▋▌▍▎▏▐', colorize: true, bgColor: '#000000', contrast: 180 }, previewImg: 'https://picsum.photos/seed/blocks_ext/400/400' },
  { id: 'glitch_pro', name: 'Glitch Pro', color: 'text-red-400', options: { mode: 'ascii', chars: ' █▓▒░◧◨◩◪◫◬◭◮', colorize: true, bgColor: '#050005', contrast: 200, saturation: 180, shadowBlur: 15, shadowColor: '#ff00ff' }, previewImg: 'https://picsum.photos/seed/glitchpro/400/400' },
  { id: 'blueprint_tech', name: 'Tech Blueprint', color: 'text-blue-400', options: { mode: 'ascii', chars: ' ─│┌┐└┘├┤┬┴┼', textColor: '#ffffff', bgColor: '#003366', invert: true, contrast: 140, spacing: 1.2 }, previewImg: 'https://picsum.photos/seed/tech/400/400' },
  { id: 'cyber_neon', name: 'Cyber Neon', color: 'text-fuchsia-400', options: { mode: 'ascii', chars: ' ░▒▓█', colorize: true, bgColor: '#000000', shadowBlur: 20, shadowColor: '#00ffff', contrast: 160, saturation: 200 }, previewImg: 'https://picsum.photos/seed/neon2/400/400' },
  { id: 'math_matrix', name: 'Math Matrix', color: 'text-emerald-400', options: { mode: 'ascii', chars: ' ±×÷√∞∟∠∡∢', textColor: '#00ff00', bgColor: '#000000', contrast: 180, brightness: 120 }, previewImg: 'https://picsum.photos/seed/mathmatrix/400/400' },
  { id: 'shapes_art', name: 'Shapes Art', color: 'text-purple-400', options: { mode: 'ascii', chars: ' ○◌◍◎●◐◑◒◓◔◕', colorize: true, bgColor: '#000000', contrast: 150, resolution: 80 }, previewImg: 'https://picsum.photos/seed/shapes/400/400' },
  { id: 'cyber_grid', name: 'Cyber Grid', color: 'text-cyan-400', options: {mode:'ascii',chars:' ┼┼',colorize:true,bgColor:'#001122',textColor:'#00ffff',contrast:150}, previewImg: 'https://picsum.photos/seed/cybergrid/400/400' },
  { id: 'neon_tokyo', name: 'Neon Tokyo', color: 'text-pink-500', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#0a001a',saturation:200,contrast:150}, previewImg: 'https://picsum.photos/seed/neontokyo/400/400' },
  { id: 'hologram', name: 'Hologram', color: 'text-cyan-300', options: {mode:'ascii',chars:' ─│┌┐└┘',textColor:'#00ffff',bgColor:'#000000',shadowBlur:10,shadowColor:'#00ffff'}, previewImg: 'https://picsum.photos/seed/hologram/400/400' },
  { id: 'synthwave', name: 'Synthwave', color: 'text-purple-500', options: {mode:'mosaic',chars:' ▲▼◀▶',colorize:true,bgColor:'#1a0033',shadowBlur:15,shadowColor:'#ff00ff'}, previewImg: 'https://picsum.photos/seed/synthwave/400/400' },
  { id: 'blood_moon', name: 'Blood Moon', color: 'text-red-600', options: {mode:'emoji',chars:'🌑🌒🌓🌔🌕🩸',bgColor:'#110000'}, previewImg: 'https://picsum.photos/seed/bloodmoon/400/400' },
  { id: 'alien_tech', name: 'Alien Tech', color: 'text-green-400', options: {mode:'ascii',chars:' ⍙⍚⍛⍜⍝⍞⍟',textColor:'#39ff14',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/alientech/400/400' },
  { id: 'matrix_red', name: 'Red Matrix', color: 'text-red-500', options: {mode:'ascii',chars:' 01',textColor:'#ff0000',bgColor:'#000000',shadowBlur:5,shadowColor:'#ff0000'}, previewImg: 'https://picsum.photos/seed/matrixred/400/400' },
  { id: 'golden_ratio', name: 'Golden Ratio', color: 'text-yellow-500', options: {mode:'ascii',chars:' φΦ',textColor:'#ffd700',bgColor:'#1a1a1a'}, previewImg: 'https://picsum.photos/seed/goldenratio/400/400' },
  { id: 'crystal', name: 'Crystal', color: 'text-cyan-200', options: {mode:'ascii',chars:' ✧✦💎',textColor:'#e0ffff',bgColor:'#001122'}, previewImg: 'https://picsum.photos/seed/crystal/400/400' },
  { id: 'steampunk', name: 'Steampunk', color: 'text-amber-700', options: {mode:'ascii',chars:' ⚙🔩🔧',textColor:'#b87333',bgColor:'#2b1d14'}, previewImg: 'https://picsum.photos/seed/steampunk/400/400' },
  { id: 'gothic_rose', name: 'Gothic Rose', color: 'text-red-800', options: {mode:'emoji',chars:'🥀🖤🦇',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/gothicrose/400/400' },
  { id: 'cyber_city', name: 'Cyber City', color: 'text-indigo-500', options: {mode:'emoji',chars:'🏙️🌃🛸',bgColor:'#050011'}, previewImg: 'https://picsum.photos/seed/cybercity/400/400' },
  { id: 'retro_wave', name: 'Retro Wave', color: 'text-purple-600', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#2d004d',contrast:180}, previewImg: 'https://picsum.photos/seed/retrowave/400/400' },
  { id: 'neon_sign', name: 'Neon Sign', color: 'text-fuchsia-500', options: {mode:'ascii',chars:' ━┃┏┓┗┛',textColor:'#ff00ff',bgColor:'#000000',shadowBlur:20,shadowColor:'#ff00ff'}, previewImg: 'https://picsum.photos/seed/neonsign/400/400' },
  { id: 'hacker_green', name: 'Hacker Green', color: 'text-green-500', options: {mode:'ascii',chars:' 0101',textColor:'#00ff00',bgColor:'#000000',contrast:200}, previewImg: 'https://picsum.photos/seed/hackergreen/400/400' },
  { id: 'vintage_sepia', name: 'Vintage Sepia', color: 'text-yellow-800', options: {mode:'ascii',chars:' ░▒▓█',textColor:'#704214',bgColor:'#f5deb3',invert:true}, previewImg: 'https://picsum.photos/seed/vintagesepia/400/400' },
  { id: 'pop_art_dots', name: 'Pop Art Dots', color: 'text-yellow-400', options: {mode:'ascii',chars:' ●',colorize:true,bgColor:'#ffff00',resolution:40}, previewImg: 'https://picsum.photos/seed/popartdots/400/400' },
  { id: 'comic_book', name: 'Comic Book', color: 'text-red-500', options: {mode:'ascii',chars:' 💥🗯️',colorize:true,bgColor:'#ffffff',invert:true}, previewImg: 'https://picsum.photos/seed/comicbook/400/400' },
  { id: 'watercolor', name: 'Watercolor', color: 'text-blue-300', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#ffffff',invert:true,saturation:150}, previewImg: 'https://picsum.photos/seed/watercolor/400/400' },
  { id: 'oil_painting', name: 'Oil Painting', color: 'text-amber-600', options: {mode:'mosaic',chars:' █',colorize:true,bgColor:'#000000',resolution:60}, previewImg: 'https://picsum.photos/seed/oilpainting/400/400' },
  { id: 'stained_glass', name: 'Stained Glass', color: 'text-indigo-400', options: {mode:'mosaic',chars:' ⬡⬢',colorize:true,bgColor:'#000000',resolution:50}, previewImg: 'https://picsum.photos/seed/stainedglass/400/400' },
  { id: 'ascii_classic', name: 'ASCII Classic', color: 'text-zinc-300', options: {mode:'ascii',chars:' .:-=+*#%@',textColor:'#ffffff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/asciiclassic/400/400' },
  { id: 'braille_dark', name: 'Braille Dark', color: 'text-zinc-500', options: {mode:'ascii',chars:' ⠁⠃⠇⡇⣇⣧⣷⣿',textColor:'#ffffff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/brailledark/400/400' },
  { id: 'binary_code', name: 'Binary Code', color: 'text-green-400', options: {mode:'ascii',chars:' 01',textColor:'#00ff00',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/binarycode/400/400' },
  { id: 'hex_code', name: 'Hex Code', color: 'text-cyan-400', options: {mode:'ascii',chars:' 0123456789ABCDEF',textColor:'#00ffff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/hexcode/400/400' },
  { id: 'dna_strand', name: 'DNA Strand', color: 'text-fuchsia-400', options: {mode:'ascii',chars:' ⚯⚮',textColor:'#ff00ff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/dnastrand/400/400' },
  { id: 'constellation', name: 'Constellation', color: 'text-blue-200', options: {mode:'ascii',chars:' ✨⋆',textColor:'#ffffff',bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/constellation/400/400' },
  { id: 'snowfall', name: 'Snowfall', color: 'text-blue-100', options: {mode:'emoji',chars:'❄️🌨️⛄',bgColor:'#001133'}, previewImg: 'https://picsum.photos/seed/snowfall/400/400' },
  { id: 'autumn', name: 'Autumn', color: 'text-orange-600', options: {mode:'emoji',chars:'🍂🍁🍄',bgColor:'#221100'}, previewImg: 'https://picsum.photos/seed/autumn/400/400' },
  { id: 'spring', name: 'Spring', color: 'text-pink-300', options: {mode:'emoji',chars:'🌸🌺🌷',bgColor:'#112200'}, previewImg: 'https://picsum.photos/seed/spring/400/400' },
  { id: 'summer', name: 'Summer', color: 'text-yellow-400', options: {mode:'emoji',chars:'☀️🏖️🌊',bgColor:'#002233'}, previewImg: 'https://picsum.photos/seed/summer/400/400' },
  { id: 'volcano', name: 'Volcano', color: 'text-red-600', options: {mode:'emoji',chars:'🌋🔥☄️',bgColor:'#220000'}, previewImg: 'https://picsum.photos/seed/volcano/400/400' },
  { id: 'thunder', name: 'Thunder', color: 'text-yellow-300', options: {mode:'emoji',chars:'⚡⛈️🌩️',bgColor:'#000011'}, previewImg: 'https://picsum.photos/seed/thunder/400/400' },
  { id: 'tornado', name: 'Tornado', color: 'text-zinc-400', options: {mode:'emoji',chars:'🌪️💨',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/tornado/400/400' },
  { id: 'earthquake', name: 'Earthquake', color: 'text-amber-800', options: {mode:'emoji',chars:'💥🏚️',bgColor:'#221100'}, previewImg: 'https://picsum.photos/seed/earthquake/400/400' },
  { id: 'tsunami', name: 'Tsunami', color: 'text-blue-500', options: {mode:'emoji',chars:'🌊💦',bgColor:'#001122'}, previewImg: 'https://picsum.photos/seed/tsunami/400/400' },
  { id: 'meteor', name: 'Meteor', color: 'text-orange-500', options: {mode:'emoji',chars:'☄️🌠',bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/meteor/400/400' },
  { id: 'black_hole', name: 'Black Hole', color: 'text-zinc-900', options: {mode:'emoji',chars:'🌌⚫',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/blackhole/400/400' },
  { id: 'supernova', name: 'Supernova', color: 'text-purple-400', options: {mode:'emoji',chars:'💥✨',bgColor:'#110022'}, previewImg: 'https://picsum.photos/seed/supernova/400/400' },
  { id: 'nebula', name: 'Nebula', color: 'text-fuchsia-600', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#1a0033',saturation:200}, previewImg: 'https://picsum.photos/seed/nebula/400/400' },
  { id: 'galaxy', name: 'Galaxy', color: 'text-indigo-300', options: {mode:'ascii',chars:' ✧✦★',colorize:true,bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/galaxy/400/400' },
  { id: 'milky_way', name: 'Milky Way', color: 'text-zinc-200', options: {mode:'ascii',chars:' .:-=+*#%@',colorize:true,bgColor:'#000011'}, previewImg: 'https://picsum.photos/seed/milkyway/400/400' },
  { id: 'solar_system', name: 'Solar System', color: 'text-yellow-500', options: {mode:'emoji',chars:'☀️🌍🌕',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/solarsystem/400/400' },
  { id: 'alien_planet', name: 'Alien Planet', color: 'text-green-600', options: {mode:'emoji',chars:'🪐👽🛸',bgColor:'#001100'}, previewImg: 'https://picsum.photos/seed/alienplanet/400/400' },
  { id: 'robot_army', name: 'Robot Army', color: 'text-zinc-500', options: {mode:'emoji',chars:'🤖🦾',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/robotarmy/400/400' },
  { id: 'cyborg', name: 'Cyborg', color: 'text-zinc-400', options: {mode:'emoji',chars:'🦾🦿',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/cyborg/400/400' },
  { id: 'ai_brain', name: 'AI Brain', color: 'text-pink-400', options: {mode:'emoji',chars:'🧠⚡',bgColor:'#001122'}, previewImg: 'https://picsum.photos/seed/aibrain/400/400' },
  { id: 'quantum', name: 'Quantum', color: 'text-cyan-500', options: {mode:'ascii',chars:' 01',colorize:true,bgColor:'#000011'}, previewImg: 'https://picsum.photos/seed/quantum/400/400' },
  { id: 'vr_world', name: 'VR World', color: 'text-purple-500', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#000000',shadowBlur:10,shadowColor:'#00ffff'}, previewImg: 'https://picsum.photos/seed/vrworld/400/400' },
  { id: 'ar_vision', name: 'AR Vision', color: 'text-blue-500', options: {mode:'ascii',chars:' ─│┌┐└┘',colorize:true,bgColor:'#ffffff',invert:true}, previewImg: 'https://picsum.photos/seed/arvision/400/400' },
  { id: 'metaverse', name: 'Metaverse', color: 'text-fuchsia-500', options: {mode:'mosaic',chars:' █',colorize:true,bgColor:'#000000',resolution:40}, previewImg: 'https://picsum.photos/seed/metaverse/400/400' },
  { id: 'blockchain', name: 'Blockchain', color: 'text-zinc-300', options: {mode:'ascii',chars:' ⛓️🔗',textColor:'#ffffff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/blockchain/400/400' },
  { id: 'crypto', name: 'Crypto', color: 'text-yellow-500', options: {mode:'emoji',chars:'💰🪙',bgColor:'#111100'}, previewImg: 'https://picsum.photos/seed/crypto/400/400' },
  { id: 'nft_art', name: 'NFT Art', color: 'text-purple-400', options: {mode:'mosaic',chars:' ⬡',colorize:true,bgColor:'#000000',resolution:50}, previewImg: 'https://picsum.photos/seed/nftart/400/400' },
  { id: 'web3', name: 'Web3', color: 'text-cyan-400', options: {mode:'ascii',chars:' 🌐💻',textColor:'#00ffff',bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/web3/400/400' },
  { id: 'security', name: 'Security', color: 'text-green-500', options: {mode:'ascii',chars:' 🔒🛡️',textColor:'#00ff00',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/security/400/400' },
  { id: 'data_breach', name: 'Data Breach', color: 'text-red-600', options: {mode:'ascii',chars:' ⚠️🚨',textColor:'#ff0000',bgColor:'#110000'}, previewImg: 'https://picsum.photos/seed/databreach/400/400' },
  { id: 'firewall', name: 'Firewall', color: 'text-orange-500', options: {mode:'ascii',chars:' 🧱🔥',textColor:'#ff4500',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/firewall/400/400' },
  { id: 'virus', name: 'Virus', color: 'text-lime-500', options: {mode:'emoji',chars:'🦠☣️',bgColor:'#001100'}, previewImg: 'https://picsum.photos/seed/virus/400/400' },
  { id: 'malware', name: 'Malware', color: 'text-red-500', options: {mode:'ascii',chars:' ☠️💀',textColor:'#ff0000',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/malware/400/400' },
  { id: 'ransomware', name: 'Ransomware', color: 'text-red-700', options: {mode:'emoji',chars:'💰🔒',bgColor:'#110000'}, previewImg: 'https://picsum.photos/seed/ransomware/400/400' },
  { id: 'phishing', name: 'Phishing', color: 'text-blue-400', options: {mode:'emoji',chars:'🎣📧',bgColor:'#001122'}, previewImg: 'https://picsum.photos/seed/phishing/400/400' },
  { id: 'spam', name: 'Spam', color: 'text-zinc-500', options: {mode:'emoji',chars:'🗑️🚫',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/spam/400/400' },
  { id: 'ddos', name: 'DDoS', color: 'text-red-600', options: {mode:'ascii',chars:' 💥🔥',textColor:'#ff0000',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/ddos/400/400' },
  { id: 'botnet', name: 'Botnet', color: 'text-indigo-900', options: {mode:'emoji',chars:'🤖🕸️',bgColor:'#000011'}, previewImg: 'https://picsum.photos/seed/botnet/400/400' },
  { id: 'zero_day', name: 'Zero Day', color: 'text-fuchsia-600', options: {mode:'ascii',chars:' 0️⃣💥',textColor:'#ff00ff',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/zeroday/400/400' },
  { id: 'exploit', name: 'Exploit', color: 'text-green-400', options: {mode:'ascii',chars:' 🔓💻',textColor:'#00ff00',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/exploit/400/400' },
  { id: 'patch', name: 'Patch', color: 'text-emerald-500', options: {mode:'emoji',chars:'🩹🛠️',bgColor:'#001100'}, previewImg: 'https://picsum.photos/seed/patch/400/400' },
  { id: 'update', name: 'Update', color: 'text-blue-500', options: {mode:'emoji',chars:'🔄⬇️',bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/update/400/400' },
  { id: 'upgrade', name: 'Upgrade', color: 'text-purple-500', options: {mode:'emoji',chars:'⬆️🚀',bgColor:'#110022'}, previewImg: 'https://picsum.photos/seed/upgrade/400/400' },
  { id: 'downgrade', name: 'Downgrade', color: 'text-red-800', options: {mode:'emoji',chars:'⬇️📉',bgColor:'#220000'}, previewImg: 'https://picsum.photos/seed/downgrade/400/400' },
  { id: 'crash', name: 'Crash', color: 'text-red-600', options: {mode:'emoji',chars:'💥🔥',bgColor:'#110000'}, previewImg: 'https://picsum.photos/seed/crash/400/400' },
  { id: 'reboot', name: 'Reboot', color: 'text-zinc-400', options: {mode:'emoji',chars:'🔄🔌',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/reboot/400/400' },
  { id: 'shutdown', name: 'Shutdown', color: 'text-zinc-600', options: {mode:'emoji',chars:'🛑🔌',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/shutdown/400/400' },
  { id: 'startup', name: 'Startup', color: 'text-green-500', options: {mode:'emoji',chars:'🚀🟢',bgColor:'#001100'}, previewImg: 'https://picsum.photos/seed/startup/400/400' },
  { id: 'login', name: 'Login', color: 'text-blue-400', options: {mode:'emoji',chars:'🔑🚪',bgColor:'#000022'}, previewImg: 'https://picsum.photos/seed/login/400/400' },
  { id: 'logout', name: 'Logout', color: 'text-orange-600', options: {mode:'emoji',chars:'🚪🚶',bgColor:'#220000'}, previewImg: 'https://picsum.photos/seed/logout/400/400' },
  { id: 'register', name: 'Register', color: 'text-emerald-400', options: {mode:'emoji',chars:'📝✅',bgColor:'#001100'}, previewImg: 'https://picsum.photos/seed/register/400/400' },
  { id: 'profile', name: 'Profile', color: 'text-zinc-300', options: {mode:'emoji',chars:'👤🖼️',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/profile/400/400' },
  { id: 'settings', name: 'Settings', color: 'text-zinc-500', options: {mode:'emoji',chars:'⚙️🔧',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/settings/400/400' },
  { id: 'dashboard', name: 'Dashboard', color: 'text-cyan-500', options: {mode:'emoji',chars:'📊📈',bgColor:'#001122'}, previewImg: 'https://picsum.photos/seed/dashboard/400/400' },
  { id: 'analytics', name: 'Analytics', color: 'text-purple-400', options: {mode:'emoji',chars:'📉📊',bgColor:'#110022'}, previewImg: 'https://picsum.photos/seed/analytics/400/400' },
  { id: 'metrics', name: 'Metrics', color: 'text-zinc-400', options: {mode:'emoji',chars:'📏📐',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/metrics/400/400' },
  { id: 'statistics', name: 'Statistics', color: 'text-zinc-600', options: {mode:'emoji',chars:'📈📉',bgColor:'#111111'}, previewImg: 'https://picsum.photos/seed/statistics/400/400' },
  { id: 'data_viz', name: 'Data Viz', color: 'text-fuchsia-400', options: {mode:'mosaic',chars:' █',colorize:true,bgColor:'#000000',resolution:30}, previewImg: 'https://picsum.photos/seed/dataviz/400/400' },
  { id: 'infographic', name: 'Infographic', color: 'text-blue-500', options: {mode:'ascii',chars:' ░▒▓█',colorize:true,bgColor:'#ffffff',invert:true}, previewImg: 'https://picsum.photos/seed/infographic/400/400' },
  { id: 'chart', name: 'Chart', color: 'text-green-400', options: {mode:'ascii',chars:' 📊📈',textColor:'#00ff00',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/chart/400/400' },
  { id: 'graph', name: 'Graph', color: 'text-red-500', options: {mode:'ascii',chars:' 📉📊',textColor:'#ff0000',bgColor:'#000000'}, previewImg: 'https://picsum.photos/seed/graph/400/400' }
];
